/**
 * This code was generated by Builder.io.
 */
import React from "react";

const About: React.FC = () => {
  return (
    <section className="flex gap-10 items-center py-24 max-md:max-w-full">
      <div className="flex flex-col self-stretch my-auto min-w-[240px] max-md:max-w-full">
        <h2 className="text-5xl font-bold leading-loose text-gray-100">
          About <span className="text-yellow-500">Me</span>
        </h2>
        <div className="flex flex-col mt-8 text-base max-md:max-w-full">
          <div className="flex flex-col text-gray-500 max-md:max-w-full">
            <p className="leading-7 max-md:max-w-full">
              I am a masters student in computer science with bachelors in
              textiles engineering I am passionate about projects that intersect
              art and sciences.
            </p>
            <p className="mt-5 leading-loose">Let me know your feed back.</p>
          </div>
          <a
            href="#contact"
            className="inline-block gap-2.5 self-start px-5 py-4 mt-10 leading-loose text-black bg-yellow-500 rounded"
          >
            Contact us
          </a>
        </div>
      </div>
    </section>
  );
};

export default About;
