/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  const socialIcons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/09fefc1e221508129e95a86f75fcddfd700be5fd915ac832087d528381b219c0?placeholderIfAbsent=true&apiKey=3cdef82382f84032880d8d1335a3f84a",
      alt: "Social media icon 1",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/275deee896c21ec6b96a82438e7c4b44b357296b870cbafd6d2a3ff8809780fc?placeholderIfAbsent=true&apiKey=3cdef82382f84032880d8d1335a3f84a",
      alt: "Social media icon 2",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/36b6df890e0b1cf9e78bf719da526e58c7797c272090312f02abb06c124a1204?placeholderIfAbsent=true&apiKey=3cdef82382f84032880d8d1335a3f84a",
      alt: "Social media icon 3",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/5e718cb2aef4254acca0657a6abf300747cc0bf78e65ae9f5e5c959cfc231b75?placeholderIfAbsent=true&apiKey=3cdef82382f84032880d8d1335a3f84a",
      alt: "Social media icon 4",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/71de5c76404886ce6ce6fd3d80f3f881e631c4251f663dabc24a8c87ac51f727?placeholderIfAbsent=true&apiKey=3cdef82382f84032880d8d1335a3f84a",
      alt: "Social media icon 5",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/a0ad0a057af45060b635c6df40fc277dbb81404226e8b9f1623cbf283840193e?placeholderIfAbsent=true&apiKey=3cdef82382f84032880d8d1335a3f84a",
      alt: "Social media icon 6",
    },
  ];

  return (
    <footer className="flex flex-col items-center py-14 max-w-full w-[685px]">
      <div className="flex flex-col items-center w-full text-center">
        <h2 className="text-4xl font-bold text-white">AboutMe.</h2>
        <p className="mt-6 text-base leading-loose text-gray-400 max-md:max-w-full">
          Mahtab Masoudi Nezhad 2024
        </p>
      </div>
      <div className="flex gap-4 items-start mt-14 max-md:mt-10">
        {socialIcons.map((icon, index) => (
          <img
            key={index}
            loading="lazy"
            src={icon.src}
            alt={icon.alt}
            className="object-contain shrink-0 w-6 aspect-square"
          />
        ))}
      </div>
    </footer>
  );
};

export default Footer;
