/**
 * This code was generated by Builder.io.
 */
import React from "react";

type HeaderProps = {
  activeLink: string;
};

const Header: React.FC<HeaderProps> = ({ activeLink }) => {
  const navItems = [
    { label: "Home", link: "#home" },
    { label: "About", link: "#about" },
    { label: "Service", link: "#service" },
    { label: "Projects", link: "#projects" },
    { label: "Resume", link: "#resume" },
    { label: "Blog", link: "#blog" },
    { label: "Contact", link: "#contact" },
  ];

  return (
    <header className="flex flex-col justify-center items-center self-stretch px-2 py-4 w-full max-md:max-w-full">
      <nav className="flex flex-wrap gap-10 items-center max-md:max-w-full">
        <h1 className="self-stretch my-auto text-2xl font-bold text-white">
          About<span className="text-yellow-500">Me.</span>
        </h1>
        <ul className="flex flex-wrap gap-7 items-start self-stretch my-auto text-base text-gray-400 uppercase whitespace-nowrap min-w-[240px] max-md:max-w-full">
          {navItems.map((item) => (
            <li key={item.label}>
              <a
                href={item.link}
                className={
                  activeLink === item.label.toLowerCase() ? "text-white" : ""
                }
              >
                {item.label}
              </a>
            </li>
          ))}
        </ul>
      </nav>
    </header>
  );
};

export default Header;
