/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Hero: React.FC = () => {
  return (
    <section className="flex overflow-hidden flex-col justify-center self-stretch py-24 pr-20 pl-40 w-full bg-gray-900 max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 items-center max-md:max-w-full">
        <div className="flex flex-col self-stretch my-auto min-w-[240px] w-[477px] max-md:max-w-full">
          <p className="text-base leading-loose text-yellow-500">
            Hello, Welcome
          </p>
          <div className="flex flex-col mt-6 max-w-full w-[477px]">
            <h2 className="text-5xl font-bold leading-loose text-gray-100">
              I'm Mahtab.
            </h2>
            <p className="mt-2 text-base leading-7 text-gray-500 max-md:max-w-full">
              I am a masters student in computer science with bachelors in
              textiles engineering I am passionate about projects that intersect
              art and sciences.
            </p>
          </div>
          <a
            href="#contact"
            className="inline-block gap-2.5 self-start px-5 py-2 mt-6 text-base leading-loose text-black bg-yellow-400 rounded"
          >
            Contact us
          </a>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/77f54ab9b4729483b30288ac61e833381c42991c0693da23a4fcf9218ee01faf?placeholderIfAbsent=true&apiKey=3cdef82382f84032880d8d1335a3f84a"
          alt="Mahtab's portrait"
          className="object-contain self-stretch my-auto rounded-3xl aspect-[0.96] min-w-[240px] w-[503px] max-md:max-w-full"
        />
      </div>
    </section>
  );
};

export default Hero;
