/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";

type LayoutProps = {
  children: React.ReactNode;
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex overflow-hidden flex-col items-center bg-slate-950">
      <Header activeLink="home" />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
